# Secret Manager — the single source of truth for every Buzz credential.
#
# Deliberate split, and the reason for it:
#
#   Terraform manages the VERSION for DATABASE_URL / READ_DATABASE_URL /
#   REDIS_URL. Their components (the Cloud SQL password Terraform generated,
#   the Memorystore AUTH string Google generated) are already in Terraform
#   state, so writing them here exposes nothing new.
#
#   Terraform creates only the CONTAINER for the relay identity key, the git
#   hook HMAC and the MinIO credentials. Those are generated by
#   `buzzctl secrets init`, which writes the version through the API and never
#   lets the value touch Terraform state or a plan file. The relay private key
#   is the workspace's cryptographic identity — rotating it changes who the
#   relay *is* — and it must not be recoverable by anyone who can read state.
#
# Replication is user-managed and pinned to the platform region so secret
# payloads never leave the jurisdiction the rest of the data lives in.

locals {
  # Managed end-to-end by Terraform.
  managed_secrets = merge(
    {
      "database-url" = var.database_url
      "redis-url"    = var.redis_url
    },
    var.read_database_url != "" ? { "read-database-url" = var.read_database_url } : {},
  )

  # Container only — populated out-of-band by buzzctl.
  externally_populated_secrets = {
    "relay-private-key" = "64-char hex Nostr secret key. The relay's identity; rotation is an identity change, not a credential refresh."
    "git-hook-hmac"     = "32+ char shared secret for git hook authentication. Required whenever replicaCount > 1."
    "minio-access-key"  = "MinIO access key the relay uses as BUZZ_S3_ACCESS_KEY."
    "minio-secret-key"  = "MinIO secret key the relay uses as BUZZ_S3_SECRET_KEY."
    "minio-root-user"   = "MinIO root user. Used by the bucket-init job and break-glass access only."
    "minio-root-password" = "MinIO root password."
    "klipy-api-key"     = "Optional KLIPY GIF search key. Leave with no version to keep GIF search disabled."
  }

  all_secret_ids = concat(
    [for k in keys(local.managed_secrets) : k],
    [for k in keys(local.externally_populated_secrets) : k],
  )
}

resource "google_secret_manager_secret" "managed" {
  for_each = local.managed_secrets

  project   = var.project_id
  secret_id = "${var.name_prefix}-${each.key}"
  labels    = var.labels

  replication {
    user_managed {
      replicas {
        location = var.region

        dynamic "customer_managed_encryption" {
          for_each = var.kms_key_id != "" ? [1] : []
          content {
            kms_key_name = var.kms_key_id
          }
        }
      }
    }
  }
}

resource "google_secret_manager_secret_version" "managed" {
  for_each = local.managed_secrets

  secret      = google_secret_manager_secret.managed[each.key].id
  secret_data = each.value

  # Keep the previous version enabled briefly so an in-flight rollout that is
  # still reading the old value does not fail mid-upgrade.
  deletion_policy = "DISABLE"
}

resource "google_secret_manager_secret" "externally_populated" {
  for_each = local.externally_populated_secrets

  project   = var.project_id
  secret_id = "${var.name_prefix}-${each.key}"
  labels    = merge(var.labels, { populated-by = "buzzctl" })

  annotations = {
    description = each.value
  }

  replication {
    user_managed {
      replicas {
        location = var.region

        dynamic "customer_managed_encryption" {
          for_each = var.kms_key_id != "" ? [1] : []
          content {
            kms_key_name = var.kms_key_id
          }
        }
      }
    }
  }

  lifecycle {
    # `buzzctl secrets init` adds versions outside Terraform. Nothing here
    # should ever try to reconcile or destroy them.
    ignore_changes = [annotations]
  }
}

# ── Access ───────────────────────────────────────────────────────────────────
# Per-secret grants, not a project-wide secretAccessor role: the ESO identity
# can read exactly these secrets and nothing else in the project.
resource "google_secret_manager_secret_iam_member" "accessor_managed" {
  for_each = google_secret_manager_secret.managed

  project   = var.project_id
  secret_id = each.value.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${var.accessor_service_account}"
}

resource "google_secret_manager_secret_iam_member" "accessor_external" {
  for_each = google_secret_manager_secret.externally_populated

  project   = var.project_id
  secret_id = each.value.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${var.accessor_service_account}"
}
